### ISSUE TITLE
TypeError Description: Cannot read properties of undefined (reading 'toLowerCase')

### ISSUE THREAD

**Issue by mumlawski** [kiali/openshift-servicemesh-plugin#258] opened 2024-02-12 12:16 UTC
Using
OpenShift Service Mesh Console v1.79.0
OpenShift 4.13.18
Kiali v1.79.0 (d5068956c3d1144a16306b397f5ccce614c1d810)
Kiali Container v1.79.0
Service Mesh Istio Dev 1.22 (dev e91027cf0d5242e677a84e5f6f9dd1924d0175c5)
Istio Dev 1.22 (dev e91027cf0d5242e677a84e5f6f9dd1924d0175c5)
Kubernetes v1.26.11+7dfc52e

When trying to get ServiceMesh details from under deployments getting below error:

TypeError
Description:
Cannot read properties of undefined (reading 'toLowerCase')

With the associated
Component trace:
```
at n (https://console-openshift-console.apps.REDUCTED/api/plugins/ossmconsole/exposed-WorkloadMeshTab-chunk-945ff43bce9c27f1980d.min.js:1:12423)
    at section
    at u (https://console-openshift-console.apps.REDUCTED/static/vendor-patternfly-core-chunk-95de86ec63df25868af0.min.js:1:1368)
    at E (https://console-openshift-console.apps.REDUCTED/static/vendor-patternfly-core-chunk-95de86ec63df25868af0.min.js:1:254619)
    at n (https://console-openshift-console.apps.REDUCTED/api/plugins/ossmconsole/116-chunk-01d01cf39e7b119cf229.min.js:1:108463)
    at n (https://console-openshift-console.apps.REDUCTED/api/plugins/ossmconsole/exposed-WorkloadMeshTab-chunk-945ff43bce9c27f1980d.min.js:1:93167)
    at S (https://console-openshift-console.apps.REDUCTED/static/vendors~main-chunk-46633dfbc3d3e0d5890f.min.js:98:86864)
    at https://console-openshift-console.apps.REDUCTED/api/plugins/ossmconsole/876-chunk-bce3d2fbeb622d227c97.min.js:1:54026
    at div
    at a (https://console-openshift-console.apps.REDUCTED/api/plugins/ossmconsole/261-chunk-82970975e7945dc4b7ca.min.js:1:147394)
    at S (https://console-openshift-console.apps.REDUCTED/static/vendors~main-chunk-46633dfbc3d3e0d5890f.min.js:98:86864)
    at t.a (https://console-openshift-console.apps.REDUCTED/static/vendors~main-chunk-46633dfbc3d3e0d5890f.min.js:150:195888)
    at vn (https://console-openshift-console.apps.REDUCTED/api/plugins/ossmconsole/exposed-WorkloadMeshTab-chunk-945ff43bce9c27f1980d.min.js:1:99686)
    at s (https://console-openshift-console.apps.REDUCTED/static/main-chunk-db5777476d06fb678427.min.js:1:239653)
    at component
    at i (https://console-openshift-console.apps.REDUCTED/static/main-chunk-db5777476d06fb678427.min.js:1:451462)
    at t (https://console-openshift-console.apps.REDUCTED/static/vendors~main-chunk-46633dfbc3d3e0d5890f.min.js:21:67625)
    at t (https://console-openshift-console.apps.REDUCTED/static/vendors~main-chunk-46633dfbc3d3e0d5890f.min.js:21:69670)
    at Suspense
    at div
    at R (https://console-openshift-console.apps.REDUCTED/static/main-chunk-db5777476d06fb678427.min.js:1:183088)
    at N (https://console-openshift-console.apps.REDUCTED/static/main-chunk-db5777476d06fb678427.min.js:1:183536)
    at div
    at https://console-openshift-console.apps.REDUCTED/static/main-chunk-db5777476d06fb678427.min.js:1:869521
    at p.memo.t.children.e.children.t.reduxes.e.reduxes.t.reduxes.every.reduxID (https://console-openshift-console.apps.REDUCTED/static/main-chunk-db5777476d06fb678427.min.js:1:725737)
    at S (https://console-openshift-console.apps.REDUCTED/static/vendors~main-chunk-46633dfbc3d3e0d5890f.min.js:98:86864)
    at <anonymous> (https://console-openshift-console.apps.REDUCTED/static/main-chunk-db5777476d06fb678427.min.js:1:728008)
    at S (https://console-openshift-console.apps.REDUCTED/static/vendors~main-chunk-46633dfbc3d3e0d5890f.min.js:98:86864)
    at https://console-openshift-console.apps.REDUCTED/static/main-chunk-db5777476d06fb678427.min.js:1:1149081
    at i (https://console-openshift-console.apps.REDUCTED/static/main-chunk-db5777476d06fb678427.min.js:1:451462)
    at DetailsPage
    at Oe (https://console-openshift-console.apps.REDUCTED/static/main-chunk-db5777476d06fb678427.min.js:1:705176)
    at s (https://console-openshift-console.apps.REDUCTED/static/main-chunk-db5777476d06fb678427.min.js:1:239653)
    at https://console-openshift-console.apps.REDUCTED/static/main-chunk-db5777476d06fb678427.min.js:1:533439
    at S (https://console-openshift-console.apps.REDUCTED/static/vendors~main-chunk-46633dfbc3d3e0d5890f.min.js:98:86864)
    at t (https://console-openshift-console.apps.REDUCTED/static/vendors~main-chunk-46633dfbc3d3e0d5890f.min.js:21:67625)
    at t (https://console-openshift-console.apps.REDUCTED/static/vendors~main-chunk-46633dfbc3d3e0d5890f.min.js:21:69670)
    at Suspense
    at i (https://console-openshift-console.apps.REDUCTED/static/main-chunk-db5777476d06fb678427.min.js:1:451462)
    at section
    at m (https://console-openshift-console.apps.REDUCTED/static/vendor-patternfly-core-chunk-95de86ec63df25868af0.min.js:1:720427)
    at div
    at div
    at t.a (https://console-openshift-console.apps.REDUCTED/static/main-chunk-db5777476d06fb678427.min.js:1:1532613)
    at div
    at div
    at c (https://console-openshift-console.apps.REDUCTED/static/vendor-patternfly-core-chunk-95de86ec63df25868af0.min.js:1:545564)
    at d (https://console-openshift-console.apps.REDUCTED/static/vendor-patternfly-core-chunk-95de86ec63df25868af0.min.js:1:775078)
    at div
    at d (https://console-openshift-console.apps.REDUCTED/static/vendor-patternfly-core-chunk-95de86ec63df25868af0.min.js:1:458279)
    at l (https://console-openshift-console.apps.REDUCTED/static/main-chunk-db5777476d06fb678427.min.js:1:1174640)
    at https://console-openshift-console.apps.REDUCTED/static/main-chunk-db5777476d06fb678427.min.js:1:458322
    at S (https://console-openshift-console.apps.REDUCTED/static/vendors~main-chunk-46633dfbc3d3e0d5890f.min.js:98:86864)
    at main
    at div
    at v (https://console-openshift-console.apps.REDUCTED/static/vendor-patternfly-core-chunk-95de86ec63df25868af0.min.js:1:263938)
    at div
    at div
    at c (https://console-openshift-console.apps.REDUCTED/static/vendor-patternfly-core-chunk-95de86ec63df25868af0.min.js:1:62178)
    at div
    at div
    at c (https://console-openshift-console.apps.REDUCTED/static/vendor-patternfly-core-chunk-95de86ec63df25868af0.min.js:1:545564)
    at d (https://console-openshift-console.apps.REDUCTED/static/vendor-patternfly-core-chunk-95de86ec63df25868af0.min.js:1:775078)
    at div
    at d (https://console-openshift-console.apps.REDUCTED/static/vendor-patternfly-core-chunk-95de86ec63df25868af0.min.js:1:458279)
    at Un (https://console-openshift-console.apps.REDUCTED/static/vendors~main-chunk-46633dfbc3d3e0d5890f.min.js:36:183619)
    at t.default (https://console-openshift-console.apps.REDUCTED/static/main-chunk-db5777476d06fb678427.min.js:1:879214)
    at e.default (https://console-openshift-console.apps.REDUCTED/static/quick-start-chunk-7b5509826321c4fc47f9.min.js:1:3540)
    at s (https://console-openshift-console.apps.REDUCTED/static/main-chunk-db5777476d06fb678427.min.js:1:239653)
    at t.a (https://console-openshift-console.apps.REDUCTED/static/main-chunk-db5777476d06fb678427.min.js:1:1609271)
    at ee (https://console-openshift-console.apps.REDUCTED/static/main-chunk-db5777476d06fb678427.min.js:1:1627447)
    at _t (https://console-openshift-console.apps.REDUCTED/static/vendors~main-chunk-46633dfbc3d3e0d5890f.min.js:36:142373)
    at ee (https://console-openshift-console.apps.REDUCTED/static/main-chunk-db5777476d06fb678427.min.js:1:1627447)
    at ee (https://console-openshift-console.apps.REDUCTED/static/main-chunk-db5777476d06fb678427.min.js:1:1627447)
    at i (https://console-openshift-console.apps.REDUCTED/static/main-chunk-db5777476d06fb678427.min.js:1:829980)
    at t.a (https://console-openshift-console.apps.REDUCTED/static/main-chunk-db5777476d06fb678427.min.js:1:1603463)
    at t.a (https://console-openshift-console.apps.REDUCTED/static/main-chunk-db5777476d06fb678427.min.js:1:1603652)
    at t.a (https://console-openshift-console.apps.REDUCTED/static/main-chunk-db5777476d06fb678427.min.js:1:1601068)
    at te (https://console-openshift-console.apps.REDUCTED/static/main-chunk-db5777476d06fb678427.min.js:1:1627578)
    at https://console-openshift-console.apps.REDUCTED/static/main-chunk-db5777476d06fb678427.min.js:1:1630710
    at r (https://console-openshift-console.apps.REDUCTED/static/vendors~main-chunk-46633dfbc3d3e0d5890f.min.js:36:121909)
    at t (https://console-openshift-console.apps.REDUCTED/static/vendors~main-chunk-46633dfbc3d3e0d5890f.min.js:21:67625)
    at t (https://console-openshift-console.apps.REDUCTED/static/vendors~main-chunk-46633dfbc3d3e0d5890f.min.js:21:69670)
    at t (https://console-openshift-console.apps.REDUCTED/static/vendors~main-chunk-46633dfbc3d3e0d5890f.min.js:21:64230)
    at re (https://console-openshift-console.apps.REDUCTED/static/main-chunk-db5777476d06fb678427.min.js:1:1631021)
    at t.a (https://console-openshift-console.apps.REDUCTED/static/main-chunk-db5777476d06fb678427.min.js:1:803960)
    at t.a (https://console-openshift-console.apps.REDUCTED/static/main-chunk-db5777476d06fb678427.min.js:1:1078211)
    at s (https://console-openshift-console.apps.REDUCTED/static/main-chunk-db5777476d06fb678427.min.js:1:653292)
    at t.a (https://console-openshift-console.apps.REDUCTED/static/vendors~main-chunk-46633dfbc3d3e0d5890f.min.js:150:195888)
    at Suspense
```

Stack trace:
```
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at https://console-openshift-console.apps.REDUCTED/api/plugins/ossmconsole/261-chunk-82970975e7945dc4b7ca.min.js:1:127716
    at Array.forEach (<anonymous>)
    at o (https://console-openshift-console.apps.REDUCTED/api/plugins/ossmconsole/261-chunk-82970975e7945dc4b7ca.min.js:1:127643)
    at n.value (https://console-openshift-console.apps.REDUCTED/api/plugins/ossmconsole/exposed-WorkloadMeshTab-chunk-945ff43bce9c27f1980d.min.js:1:15778)
    at Ha (https://console-openshift-console.apps.REDUCTED/static/vendors~main-chunk-46633dfbc3d3e0d5890f.min.js:263:71430)
    at Ba (https://console-openshift-console.apps.REDUCTED/static/vendors~main-chunk-46633dfbc3d3e0d5890f.min.js:263:71229)
    at Hs (https://console-openshift-console.apps.REDUCTED/static/vendors~main-chunk-46633dfbc3d3e0d5890f.min.js:263:112371)
    at xl (https://console-openshift-console.apps.REDUCTED/static/vendors~main-chunk-46633dfbc3d3e0d5890f.min.js:263:98327)
    at Cl (https://console-openshift-console.apps.REDUCTED/static/vendors~main-chunk-46633dfbc3d3e0d5890f.min.js:263:98255)
    at _l (https://console-openshift-console.apps.REDUCTED/static/vendors~main-chunk-46633dfbc3d3e0d5890f.min.js:263:98118)
```

**Comment by jmazzitelli** [comment] 2024-02-12 14:08
I'm fairly sure OSSMC 0.4.0 won't work with Kiali Server 1.79.

@jshaughn @ferhoyos Perhaps we should add OSSMC in the compatibility matrix? https://staging.kiali.io/docs/installation/installation-guide/prerequisites/#version-compatibility

**Comment by ferhoyos** [comment] 2024-02-12 16:10
Current version of OSSMC (v1.79.0) only works with Kiali server 1.73.

> @jshaughn @ferhoyos Perhaps we should add OSSMC in the compatibility matrix? https://staging.kiali.io/docs/installation/installation-guide/prerequisites/#version-compatibility

Yes, it would be great to have OSSMC compatibility matrix in kialio.io page.

**Comment by ferhoyos** [comment] 2024-02-13 16:43
@mumlawski here you have OSSMC compatibility matrix in kiali documentation page :-)

https://kiali.io/docs/installation/installation-guide/prerequisites/#openshift-console-plugin-ossmc-version-compatibility

For the moment all OSSMC versions only work with Kiali server v1.73 due to library conflict with Openshift. We hope to align OSSMC to latest version of Kiali for upcoming Openshift release (version 4.15).

**Comment by ferhoyos** [comment] 2024-08-08 10:07
Closing since the issue is resolved.

From version 1.84, Kiali and OSSMC are aligned (e.g., OSSMC v1.88 works with Kiali v1.88). For older OSSMC versions, Kiali server 1.73 must be used (see compatibility matrix above).

**Closed by ferhoyos** 2024-08-08 10:07 UTC
